class CivicStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'JanSeva',
      'appTagline': 'Citizen Grievance & Public Service Delivery',
      'home': 'Home',
      'myGrievances': 'My Grievances',
      'fileGrievance': 'File Grievance',
      'analytics': 'Analytics',
      'emergency': 'Emergency',
      'schemes': 'Welfare Schemes',
      'notices': 'Ward Notices',
      'profile': 'Profile',
      'searchHint': 'Search by title, locality or ID...',
      'allWards': 'All Wards',
      'allStatuses': 'All Statuses',
      'filterBy': 'Filter by',
      'statusSubmitted': 'Submitted',
      'statusTriaged': 'Under Review',
      'statusInProgress': 'In Progress',
      'statusResolved': 'Resolved',
      'statusClosed': 'Citizen Verified',
      'statusReopened': 'Reopened',
      'slaBreached': 'SLA Breached',
      'hoursRemaining': 'hours remaining',
      'upvote': 'Upvote',
      'upvoted': 'Upvoted',
      'officerWorkspace': 'Officer Workspace',
      'citizenMode': 'Citizen Mode',
      'offlineBanner': 'Offline Mode: Data saved locally and will auto-sync.',
      'syncNow': 'Sync Now',
      'languageToggle': 'हिंदी',
      'sosTitle': 'Emergency Helplines & Civic SOS',
      'sosSubtitle': 'Urgent public hazard dispatch for immediate emergency response.',
    },
    'hi': {
      'appName': 'जनसेवा',
      'appTagline': 'नागरिक शिकायत एवं लोक सेवा वितरण प्रणाली',
      'home': 'होम',
      'myGrievances': 'मेरी शिकायतें',
      'fileGrievance': 'शिकायत दर्ज करें',
      'analytics': 'विश्लेषण',
      'emergency': 'आपातकालीन',
      'schemes': 'कल्याणकारी योजनाएं',
      'notices': 'वार्ड सूचनाएं',
      'profile': 'प्रोफ़ाइल',
      'searchHint': 'शीर्षक, क्षेत्र या आईडी द्वारा खोजें...',
      'allWards': 'सभी वार्ड',
      'allStatuses': 'सभी स्थितियां',
      'filterBy': 'फ़िल्टर करें',
      'statusSubmitted': 'दर्ज किया गया',
      'statusTriaged': 'समीक्षाधीन',
      'statusInProgress': 'कार्य प्रगति पर',
      'statusResolved': 'निस्तारित',
      'statusClosed': 'सत्यापित एवं बंद',
      'statusReopened': 'पुनः खोला गया',
      'slaBreached': 'समयसीमा समाप्त',
      'hoursRemaining': 'घंटे शेष',
      'upvote': 'समर्थन दें',
      'upvoted': 'समर्थित',
      'officerWorkspace': 'अधिकारी कार्यक्षेत्र',
      'citizenMode': 'नागरिक मोड',
      'offlineBanner': 'ऑफ़लाइन मोड: डेटा सुरक्षित है और इंटरनेट आने पर स्वतः सिंक होगा।',
      'syncNow': 'अभी सिंक करें',
      'languageToggle': 'English',
      'sosTitle': 'आपातकालीन हेल्पलाइन एवं त्वरित सहायता',
      'sosSubtitle': 'गंभीर जन सुरक्षा खतरों के लिए तत्काल आपातकालीन प्रतिक्रिया।',
    },
  };

  static String get(String key, {bool isHindi = false}) {
    final lang = isHindi ? 'hi' : 'en';
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
